---
- name: Get Vector distrib
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: ./vector-{{ vector_version }}.tar.gz
    mode: "0644"
    validate_certs: false
  tags:
    - get
- name: Create directory for Vector distrib
  ansible.builtin.file:
    path: ./vector-{{ vector_version }}
    state: directory
    mode: "0755"
  tags:
    - install
- name: Unarchive Vector distrib
  ansible.builtin.unarchive:
    src: ./vector-{{ vector_version }}.tar.gz
    dest: ./vector-{{ vector_version }}
    remote_src: true
    extra_opts:
      - --strip-components=2
  tags:
    - install
- name: Copy Vector bin file
  become: true
  ansible.builtin.copy:
    src: ./vector-{{ vector_version }}/bin/vector
    dest: /usr/bin/vector
    remote_src: true
    owner: root
    group: root
    mode: "0755"
  tags:
    - install
- name: Copy Vector default
  become: true
  ansible.builtin.copy:
    src: ./vector-{{ vector_version }}/etc/systemd/vector.default
    dest: /etc/default/vector
    remote_src: true
    owner: root
    group: root
    mode: "0644"
  tags:
    - install
- name: Create systemd system directory, in not exists
  ansible.builtin.file:
    path: /usr/lib/systemd/system
    state: directory
    mode: "0644"
  tags:
    - install
- name: Setup Vector service systemd file
  become: true
  ansible.builtin.template:
    src: templates/vector.service.j2
    dest: /usr/lib/systemd/system/vector.service
    mode: "0644"
  tags:
    - install
- name: Create directory for Vector config
  become: true
  ansible.builtin.file:
    path: /etc/vector/
    state: directory
    mode: "0644"
  tags:
    - install
- name: Create Vevtor data directory
  become: true
  ansible.builtin.file:
    path: /var/lib/vector/
    state: directory
    mode: "0644"
  tags:
    - install
- name: Setup Vector config
  become: true
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: /etc/vector/vector.yaml
    mode: "0644"
  tags:
    - install
- name: Create Vector group
  become: true
  ansible.builtin.group:
    name: vector
    state: present
  tags:
    - install
- name: Create Vector user
  become: true
  ansible.builtin.user:
    name: vector
    shell: /bin/sh
    groups: vector
    append: true
  tags:
    - install
- name: Reload configs
  block:
    - name: Reload systemd configs
      become: true
      ansible.builtin.systemd:
        daemon_reload: true
      notify: Start Vector service
  rescue:
    - name: Systemd not available.
      debug:
        msg: Reload daemons skipped.
      notify: Start Vector service
  tags:
    - prepare