---
- name: Converge
  hosts: all
  gather_facts: false
  become_method: su
  tasks:
    - name: Include Vector
      include_role:
        name: ansible-role-vector-test
      vars: 
        use_dbus: false
