---
dependency:
  name: galaxy
driver:
  name: docker
#lint: |
#  ansible-lint .
#  yamllint .
platforms:
  - name: centos7
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
  - name: oraclelinux8
    image: docker.io/oraclelinux:8
    pre_build_image: true
  - name: ubuntu_latest
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
